const ROLES = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  GUEST: "GUEST",
  // SERVICE_CO_ORDINATOR: "SERVICE_CO_ORDINATOR",
};
export const ORDER_TYPE = {
  AMBULANCE: "AMBULANCE",
  PHARMACY: "PHARMACY",
  TELE_MEDICINE: "TELE_MEDICINE",
};
export const STOCK_TYPE = {
  IN: "IN",
  OUT: "OUT",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DELIVERED: "DELIVERED",
  DENIED: "DENIED",
  CANCELLED: "CANCELLED",
};

export default ROLES;
